### ISSUE TITLE
not working with latest version of WP (4.4)

### ISSUE THREAD

**Issue by foo123** [Nightgunner5/node-wordpress-auth#5]
Hello, using this module (actually part of it), but password_fragment hash authentiication,
is not working with latest wp version (4.4)

The cookie and DB user info are succesfuly fetched, but the final `parse` function that compares
the two hashes, always fails

i have a custom extract of this module for a socket applicaton which communicates with wp, so i can fix it myself.

Is there any idea where the code fails?

PS: 

browsing wp function `wp_generate_auth_cookie` there is a custom `$token` parameter used (which if missing, a kind of defauilt `SessionToken` is generated, depending on cookie type, e.g `auth`, `logged_in` and so on..)

i dont see this token info taken into account in the module `parse` function. Maybe this is the problem.

Thanx,
Nikos

**Comment by foo123** [comment]
Note, i'm using git master version cloned from this repo, not npm version.

i see this issue https://github.com/Nightgunner5/node-wordpress-auth/issues/2, has a PR which includes the token, still it is not in the version i cloned from github

**Comment by foo123** [comment]
Using this fork https://github.com/j3k0/node-wordpress-auth, solves the issue.

Closing this

**Comment by bminer** [comment]
Suggest re-opening until the new version is merged (and published to NPM)?
